# Generated by Django 5.1.7 on 2025-03-13 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_load_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stadium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=512)),
                ("guide", models.CharField(blank=True, max_length=4096, null=True)),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("five", "5x5"),
                            ("eight", "8x8"),
                            ("eleven", "11x11"),
                        ],
                        default="five",
                        max_length=128,
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("open_fields", "Open Fields"),
                            ("close_fields", "Close Fields"),
                            ("hall", "Hall"),
                        ],
                        default="open_fields",
                        max_length=128,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Price"
                    ),
                ),
                ("description", models.TextField()),
                ("opens_at", models.DateTimeField(null=True)),
                ("closes_at", models.DateTimeField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stadiums",
                        to="common.district",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stadiums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stadiums",
                        to="common.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("info", models.CharField(max_length=255)),
                (
                    "stadium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="stadion.stadium",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StadiumMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=128,
                    ),
                ),
                ("file", models.FileField(upload_to="stadium_media/")),
                (
                    "stadium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="stadion.stadium",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
